import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Providers } from '@/lib/providers/providers';
import '../shared/css/globals.css';
import '../shared/css/normalise.css';
import { NextFontWithVariable } from 'next/dist/compiled/@next/font';
import Script from 'next/script';
import { themeInitScript } from '@/shared/theme/initScript';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono: NextFontWithVariable = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <Script
                id="theme-init"
                strategy="beforeInteractive"
                dangerouslySetInnerHTML={{ __html: themeInitScript }}
            />
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
