import clsx from 'clsx';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Providers } from '@/lib/providers/providers';
import '../shared/css/globals.css';
import '../shared/css/normalise.css';
import { getRequestTheme } from '@/shared/theme/server/getRequestTheme';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    const theme = await getRequestTheme();

    return (
        <html lang="en" data-theme={theme} suppressHydrationWarning>
            <body className={clsx(geistSans.variable, geistMono.variable)}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
